name: mabe_utils
description: Utility widgets, extension methods and types used on every app developed by me (https://raulmabe.dev)
version: 0.2.0-pre

homepage: https://github.com/raulmabe/mabe_utils
repository: https://github.com/raulmabe/mabe_utils
issue_tracker: https://github.com/raulmabe/mabe_utils/issues
documentation: https://github.com/raulmabe/mabe_utils
topics: [utils, extensions, widgets, types]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  gap: ^3.0.1
  in_app_review: ^2.0.8
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^5.0.1
  provider: ^6.1.1
  sprung: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
